version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    build: ./docker
    container_name: read-file
    restart: always
    ports:
      - 27018:27018
    env_file:
      - .env
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    name: nest-db
