version: '3.8'
services:
  mongodb:
    image: mongo:4
    command: --replSet rs0
    container_name: read-file
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
volumes:
  mongodb:
    name: nest-db
